version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/commit_verify"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/commit_verify/derive"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/single_use_seals"
    schedule:
      interval: "weekly"
