[package]
name = "client_side_validation"
version = "0.9.0-alpha.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "Client-side validation foundation library"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "blockchain"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "commit_verify", "confined_encoding", "single_use_seals"]

[lib]
name = "client_side_validation"
path = "src/lib.rs"

[dependencies]
confined_encoding = { version = "0.9.0-alpha.1", path = "confined_encoding" }
commit_verify = { version = "0.9.0-alpha.1", path = "./commit_verify" }
single_use_seals = { version = "0.9.0-alpha.1", path = "./single_use_seals" }

[dev-dependencies]
async-trait = "0.1.51"

[features]
default = []
all = ["serde", "rand", "async", "bulletproofs"]
async = ["single_use_seals/async"]
rand = ["commit_verify/rand"]
serde = ["commit_verify/serde"]
bulletproofs = ["commit_verify/bulletproofs", "confined_encoding/bulletproofs"]

[package.metadata.docs.rs]
features = [ "all" ]

[workspace]
members = [".", "confined_encoding", "commit_verify", "single_use_seals",
    "confined_encoding/derive", "confined_encoding/test_helpers"]
default-members = ["."]
