[workspace]
members = [
    ".",
    "commit_verify",
    "single_use_seals"
]
default-members = [
    ".",
    "commit_verify",
    "single_use_seals"
]

[package]
name = "client_side_validation"
version = "0.9.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "Client-side validation foundation library"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "blockchain"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "commit_verify", "single_use_seals"]

[lib]
name = "client_side_validation"
path = "src/lib.rs"

[dependencies]
commit_verify = { version = "0.9.0", path = "./commit_verify" }
single_use_seals = { version = "0.9.0", path = "./single_use_seals" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde", "rand", "async", "bulletproofs"]
async = ["single_use_seals/async"]
rand = ["commit_verify/rand"]
serde = ["serde_crate", "commit_verify/serde"]
bulletproofs = ["commit_verify/bulletproofs"]

[package.metadata.docs.rs]
features = [ "all" ]

[patch.crates-io]
strict_encoding = { git = "https://github.com/strict-types/strict-encoding" }
