[package]
name = "client_side_validation"
version = "0.5.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Client-side validation foundation library"
repository = "https://github.com/LNP-BP/client_side_validation"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "blockchain"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2018"
exclude = [".github", "commit_verify", "strict_encoding", "single_use_seals"]

[lib]
name = "client_side_validation"
path = "src/lib.rs"

[dependencies]
strict_encoding = { version = "1.5.1", path = "./strict_encoding" }
commit_verify = { version = "0.5.0", path = "./commit_verify" }
single_use_seals = { version = "0.5.0", path = "./single_use_seals" }

[features]
default = []
all = ["serde", "rand", "bitcoin"]
rand = ["commit_verify/rand"]
serde = ["commit_verify/serde"]
bitcoin = ["strict_encoding/bitcoin", "strict_encoding/miniscript"]
crypto = ["strict_encoding/crypto"]

[workspace]
members = [".", "strict_encoding", "commit_verify", "single_use_seals", "strict_encoding/derive"]
default-members = [".", "strict_encoding", "commit_verify", "single_use_seals", "strict_encoding/derive"]
