[workspace]
members = [
    ".",
    "commit_verify",
    "single_use_seals"
]
default-members = [
    ".",
    "commit_verify",
    "single_use_seals"
]

[workspace.package]
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
homepage = "https://github.com/LNP-BP"
repository = "https://github.com/LNP-BP/client_side_validation"
rust-version = "1.66" # Due to strict encoding library (caused by GAD)
edition = "2021"
license = "Apache-2.0"

[package]
name = "client_side_validation"
version = "0.10.0-beta.1"
description = "Client-side validation foundation library"
keywords = ["lnp-bp", "smart-contracts", "blockchain"]
categories = ["cryptography"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = [".github", "commit_verify", "single_use_seals"]

[lib]
name = "client_side_validation"
path = "src/lib.rs"

[dependencies]
commit_verify = { version = "0.10.0-beta.1", path = "./commit_verify" }
single_use_seals = { version = "0.10.0-beta.1", path = "./single_use_seals" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }

[features]
default = []
all = ["serde", "rand", "async"]
async = ["single_use_seals/async"]
rand = ["commit_verify/rand"]
serde = ["serde_crate", "commit_verify/serde"]

[package.metadata.docs.rs]
features = [ "all" ]
