[package]
name = "commit_verify"
version = "0.10.1"
description = "Commit-verify API for client-side validation"
keywords = ["lnp-bp", "smart-contracts", "blockchain", "commitments"]
categories = ["cryptography"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"
exclude = ["derive"]

[lib]
name = "commit_verify"
path = "src/lib.rs"

[[bin]]
name = "commit-stl"
required-features = ["stl"]

[dependencies]
amplify = { version = "4.0.0-beta.20", features = ["hex", "apfloat"] }
commit_encoding_derive = { version = "0.10.0-beta.1", path = "derive" }
strict_encoding = "2.0.0"
strict_types = { version = "1.0.0-rc.1", optional = true }
rand = { version = "0.8.5", optional = true }
serde_crate = { version = "1.0", package = "serde", optional = true }

[dev-dependencies]
rand = "0.8.5"

[features]
default = ["derive"]
all = ["rand", "serde", "stl", "derive"]
serde = ["serde_crate", "amplify/serde"]
stl = ["strict_types", "strict_types/base64"]
derive = []

[package.metadata.docs.rs]
features = [ "all" ]
