[package]
name = "commit_verify"
version = "0.10.0-beta.2"
description = "Commit-verify API for client-side validation"
keywords = ["lnp-bp", "smart-contracts", "blockchain", "commitments"]
categories = ["cryptography"]
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
readme = "README.md"

[lib]
name = "commit_verify"
path = "src/lib.rs"

[dependencies]
amplify = { version = "4.0.0-beta.10", features = ["hex", "apfloat"] }
bitcoin_hashes = "0.11.0"
strict_encoding = "2.0.0-beta.5"
rand = { version = "0.8.5", optional = true }
serde_crate = { version = "1.0", package = "serde", optional = true }

[dev-dependencies]
rand = "0.8.5"

[features]
default = []
all = ["rand", "serde"]
serde = ["serde_crate", "bitcoin_hashes/serde", "amplify/serde"]

[package.metadata.docs.rs]
features = [ "all" ]
