name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+\.*'
  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --workspace
  no-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --workspace --no-default-features
  features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: [ derive, stl, serde, async, rand ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Feature ${{matrix.feature}}
        run: cargo check --workspace --no-default-features --features=${{matrix.feature}}
      - name: Feature ${{matrix.feature}}
        run: cargo check --workspace --features=${{matrix.feature}}
  platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-latest, macos-13, macos-latest, windows-2019, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Platform ${{matrix.os}}
        run: cargo check --workspace --all-features # we skip test targets here to be sure that the main library can be built
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ nightly, beta, stable ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.toolchain}}
      - name: Toolchain ${{matrix.toolchain}}
        run: cargo +${{matrix.toolchain}} check --workspace --all-targets --all-features
  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SebRollen/toml-action@v1.2.0
        id: msrv
        with:
          file: 'Cargo.toml'
          field: 'workspace.rust-version'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{steps.msrv.outputs.value}}
      - name: Toolchain ${{steps.msrv.outputs.value}}
        run: cargo +${{steps.msrv.outputs.value}} check --workspace --all-targets --all-features
